'use client'

import { Card, CardContent } from "@/components/ui/card"
import {
  Heart,
  Bike,
  Music,
  Book,
  Plane,
  Camera,
  Soup,
  Dumbbell,
  Sun,
  Clapperboard,
  CupSoda,
  IndianRupee,
  ChevronDown,
  ChevronUp
} from "lucide-react"
import Image from "next/image"
import { useState } from "react"

export default function AboutMe() {
  const [expandedFact, setExpandedFact] = useState<number | null>(null);
  const [hoveredInterest, setHoveredInterest] = useState<number | null>(null);

  const interests = [
    { name: "Photography", icon: <Camera className="h-5 w-5" /> },
    { name: "Traveling", icon: <Plane className="h-5 w-5" /> },
    { name: "Reading", icon: <Book className="h-5 w-5" /> },
    { name: "Music", icon: <Music className="h-5 w-5" /> },
    { name: "Bike Riding", icon: <Bike className="h-5 w-5" /> },
    { name: "Cooking", icon: <Soup className="h-5 w-5" /> },
    { name: "Fitness", icon: <Dumbbell className="h-5 w-5" /> },
    { name: "Chai Lover", icon: <CupSoda className="h-5 w-5" /> },
    { name: "Bollywood", icon: <Clapperboard className="h-5 w-5" /> },
    { name: "Beaches", icon: <Sun className="h-5 w-5" /> },
    { name: "Cricket", icon: <Heart className="h-5 w-5" /> },
    { name: "SRK Fan", icon: <IndianRupee className="h-5 w-5" /> },
  ]

  const funFacts = [
    { title: "Bangalore Roots", description: "I've lived in Ahmedabad my whole life, but my heart still says \"Namma Bengaluru\" ❤️." },
    { title: "Bollywood Fanatic", description: "Have watched Kuch Kuch Hota Hai a gazillion times and can quote every dialogue 😌." },
    { title: "Home Chef", description: "I can cook a pretty good meal for four (bonus: I clean as I cook) 🍽️." },
    { title: "Cricket Obsession", description: "Had not skipped a single ball of Kohli in 2016 IPL. Ask me any stat from that season! 🏏🔥" },
    { title: "Music Therapy", description: "Old Hindi songs calm me down like nothing else. I have playlists for every mood 🎧🕊️." }
  ];

  const toggleFact = (index: number) => {
    if (expandedFact === index) {
      setExpandedFact(null);
    } else {
      setExpandedFact(index);
    }
  };

  return (
    <div className="container mx-auto px-4 py-12 bg-gray-50">
      <div className="max-w-4xl mx-auto">
        <h2 className="text-4xl font-bold mb-2 text-center bg-gradient-to-r from-emerald-600 to-teal-500 bg-clip-text text-transparent">A Little Bit About Me: No Filter</h2>
        <div className="w-24 h-1 bg-gradient-to-r from-emerald-500 to-teal-400 mx-auto mb-12 rounded-full"></div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center mb-16 bg-white rounded-xl p-6 shadow-lg">
          <div className="relative h-96 w-full rounded-lg overflow-hidden shadow-md transform transition-transform hover:scale-102 duration-300">
            <Image src="/image3.jpg" alt="Profile" fill className="object-cover" />
            <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent flex items-end">
              <p className="text-white p-4 font-medium text-lg">Just a fun loving guy ✨</p>
            </div>
          </div>
          <div>
            <h3 className="text-2xl font-bold mb-4 flex items-center">
              <span className="bg-emerald-100 text-emerald-700 p-2 rounded-full mr-2">👋</span>
              Who I Am
            </h3>
            <div className="space-y-4 text-gray-700">
              <p>
                Hey! I'm originally from Bangalore but have spent most of my life in Ahmedabad. I'm pretty talkative, fun-loving, and I somehow always find myself vibing to Hindi music 🎶 or zoning out in my own little world 🌈. If there's a group of people laughing loudly somewhere, I'm probably in the middle of it.
              </p>
              <p>
                🎬 I'm a total Bollywood junkie and a massive SRK fan (no debates, he's the Badshah 👑). Feel-good movies and thrillers are my jam, and romantic movies? They're usually comedy to me—unless, of course, it's Shah Rukh doing the romancing.
              </p>
              <p>
                🏋️‍♂️ When I'm not working, you'll find me either lifting weights at the gym, out on a bike ride 🏍️. I'm more of a chai guy than coffee; beaches over mountains. And music? Can't go a day without it.
              </p>
              <p>
                🍳 Oh, and I love cooking! Nothing too fancy, but I can put together a solid meal for four people (and yeah, I do the dishes too 😄).
              </p>
              <p className="italic border-l-4 border-emerald-300 pl-3">
                ~Generated by ChatGPT, improvised by me 😉.
              </p>
            </div>
          </div>
        </div>

        <h3 className="text-3xl font-bold mb-8 text-center">What I'm Into</h3>
        
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4 mb-16">
          {interests.map((interest, index) => (
            <div
              key={index}
              className="flex flex-col items-center p-5 bg-white rounded-xl shadow-sm border border-gray-100 transition-all duration-300 hover:shadow-md hover:border-emerald-200"
              onMouseEnter={() => setHoveredInterest(index)}
              onMouseLeave={() => setHoveredInterest(null)}
            >
              <div 
                className={`p-4 rounded-full mb-3 transition-all duration-300 ${
                  hoveredInterest === index 
                    ? 'bg-emerald-500 text-white scale-110' 
                    : 'bg-emerald-100 text-emerald-600'
                }`}
              >
                {interest.icon}
              </div>
              <span className={`text-sm font-medium transition-all duration-300 ${
                hoveredInterest === index ? 'text-emerald-600' : ''
              }`}>
                {interest.name}
              </span>
            </div>
          ))}
        </div>

        <div className="mb-16">
          <h3 className="text-3xl font-bold mb-8 text-center">Fun Facts About Me 🎉</h3>
          <div className="space-y-4">
            {funFacts.map((fact, index) => (
              <Card 
                key={index} 
                className={`overflow-hidden transition-all duration-300 ${
                  expandedFact === index ? 'border-emerald-300 shadow-md' : 'hover:border-emerald-200'
                }`}
              >
                <div 
                  className="p-4 flex justify-between items-center cursor-pointer"
                  onClick={() => toggleFact(index)}
                >
                  <h4 className="font-bold text-lg">{fact.title}</h4>
                  <button className="text-emerald-600 p-1 rounded-full hover:bg-emerald-50">
                    {expandedFact === index ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                  </button>
                </div>
                <div className={`overflow-hidden transition-all duration-300 ${
                  expandedFact === index ? 'max-h-40' : 'max-h-0'
                }`}>
                  <CardContent className="pt-0 pb-4">
                    <p className="text-gray-700">{fact.description}</p>
                  </CardContent>
                </div>
              </Card>
            ))}
          </div>
        </div>

        
      </div>
    </div>
  )
}